server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://adam.cpiq8808qo9q.ap-northeast-2.rds.amazonaws.com:3306/talktok
    username: talktok
    password: choongang

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

<<<<<<< HEAD:src/main/resources/application.yaml
  mail:
    hostSMTPid: aircamp03@naver.com
    hostSMTPpwd: aircamp123123

=======
    open-in-view: false
  devtools:
    livereload:
      enabled: true
>>>>>>> 673b8f51a6f48018dff5d9778b809e802f3bec39:src/main/resources/application.yml

